/**
 * @file icraft_errno.h
 * @author Junkun Wang (wangjunkun@fmsh.com.cn)
 * @brief Icraft3.x error code
 * @date 2024-04-10
 * 
 * @copyright Copyright (c) 2023 Shanghai Fudan Microelectronics Group Co., Ltd. All rights reserved.
 * 
 */

#ifndef ICRAFT_ERROR_H
#define ICRAFT_ERROR_H

typedef enum{
    ICRAFT_SUCCESS                                = 0,
    // device
    ICRAFT_DEVICE_RESET_ERROR                     = 10000,
    ICRAFT_DEVICE_NOT_OPEN                        = 10001,
    ICRAFT_DEVICE_REG_ADDR_OUT_OF_BOUND           = 10002,
    ICRAFT_DEVICE_INVALID_RESET_LEVEL             = 10003,
    ICRAFT_DEVICE_CDMA_ERROR                      = 10004,
    ICRAFT_DEVICE_CDMA_TIMEOUT                    = 10005,
    ICRAFT_DEVICE_MALLOC_ERROR                    = 10006,
    ICRAFT_DEVICE_DMA_DATA_NOT_SAME               = 10007,
    ICRAFT_DEVICE_AICORE_INVALID_ADDR             = 10008,
    ICRAFT_DEVICE_AICORE_INVALID_SIZE             = 10009,
    ICRAFT_DEVICE_GET_LAYERCOUNT_FAIL             = 10010,
    ICRAFT_DEVICE_SET_DTYPE_FAIL                  = 10011,
    ICRAFT_DEVICE_INVALID_DTYPE                   = 10012,
    ICRAFT_DEVICE_INVALID_ICORE_FREQ              = 10013,
    ICRAFT_DEVICE_ENABLE_MPE_FAIL                 = 10014,
    ICRAFT_DEVICE_INVALID_MPE_PARAM               = 10015,
    ICRAFT_DEVICE_GET_MMU_MODE_FAIL               = 10016,
    ICRAFT_DEVICE_OPEN_MMU_FAIL                   = 10017,
    ICRAFT_DEVICE_CLOSE_MMU_FAIL                  = 10018,
    ICRAFT_DEVICE_MMU_UNKNOWN_MODE                = 10019,
    ICRAFT_DEVICE_READ_CDMA_FAIL                  = 10020,
    ICRAFT_DEVICE_WRITE_CDMA_FAIL                 = 10021,
    ICRAFT_DEVICE_MMU_IDX_OUT_OF_RANGE            = 10022,    
    // network
    ICRAFT_NETWORK_LOAD_FILE_FAIL                 = 20001,
    ICRAFT_NETWORK_MALLOC_FAIL                    = 20002,
    ICRAFT_NETWORK_UNPACK_BUFFER_UNACCESSIABLE    = 20003,
    ICRAFT_NETWORK_UNSUPPORT_OP_TYPE              = 20004,
    ICRAFT_NETWORK_NORMRATIO_NUM_DISMATCH         = 20005,
    ICRAFT_NETWORK_NO_OPS                         = 20006,
    ICRAFT_NETWORK_CREATE_OPS_TYPE_FAIL           = 20007,
    ICRAFT_NETWORK_FORWARD_OPS_NUM_DISMATCH       = 20008,
    ICRAFT_NETWORK_UPLOAD_FAIL                    = 20009,
    ICRAFT_NETWORK_BUFFER_NUM_OUT_OF_BOUNDS       = 20010,
    ICRAFT_NETWORK_BUFFER_NULL                    = 20011,
    ICRAFT_NETWORK_GET_FTMP_FAIL                  = 20012,
    ICRAFT_NETWORK_INPUT_IDX_OUT_OF_BOUNDS        = 20013,
    ICRAFT_NETWORK_INVALID_MYTPE                  = 20014,   
    ICRAFT_NETWORK_FORWARD_FAIL                   = 20015,
    ICRAFT_NETWORK_NOT_INITIAL                    = 20016,
    ICRAFT_NETWORK_ADDR_OUT_OF_BOUND              = 20017,
    ICRAFT_NETWORK_DATA_SIZE_OUT_OF_BOUND         = 20018,
    ICRAFT_NETWORK_BUFFER_SIZE_INCONSISTENT       = 20019,
    ICRAFT_NETWORK_FILL_PLDDR_INPUT_FAIL          = 20020,
    ICRAFT_NETWORK_PREPARE_IFMS_OFMS_FAIL         = 20021,
    ICRAFT_NETWORK_DEPLOY_CHECK_FAIL              = 20022,
    ICRAFT_NETWORK_UNPACK_ADDR_NOT_ALIGNED        = 20023,
    ICRAFT_NETWORK_INIT_OP_FAIL                   = 20024,
    ICRAFT_NETWORK_DUMP_FAIL                      = 20025,
    ICRAFT_NETWORK_OPEN_MMU_FAIL                  = 20026,
    ICRAFT_NETWORK_UNSUPPORT_GIC                  = 20027,
    ICRAFT_NETWORK_NULL                           = 20028,
    ICRAFT_NETWORK_OP_NULL                        = 20029,
    ICRAFT_NETWORK_DECONSTRUCT_FAIL               = 20030,    
    // ftmp
    ICRAFT_FTMP_NOT_READY                         = 30001,
    ICRAFT_FTMP_GET_LAYERCOUNT_FAIL               = 30002,
    ICRAFT_FTMP_SYNC_FAIL                         = 30003,
    ICRAFT_FTMP_NULL                              = 30004,
    ICRAFT_FTMP_INVALID_MTYPE                     = 30005,
    ICRAFT_FTMP_GET_DATA_FAIL                     = 30006,
    ICRAFT_FTMP_GENERATE_PATH_FAIL                = 30007,
    ICRAFT_FTMP_DUMP_FAIL                         = 30008,
    ICRAFT_FTMP_NO_DATA                           = 30009,
    ICRAFT_FTMP_CREATE_DUMP_DIR_FAIL              = 30010,
    ICRAFT_FTMP_DECONSTRUCT_FAIL                  = 30011,
    // basic op
    ICRAFT_OP_NULL                                = 40001,
    ICRAFT_OP_UNKNOWN_TYPE                        = 40002,
    ICRAFT_OP_GET_NAME_BUFFER_NULL                = 40003,
    ICRAFT_OP_DECONSTRUCT_FAIL                    = 40004,
    // hardop 
    ICRAFT_HARDOP_GET_LAYERCOUNT_FAIL             = 50001,
    ICRAFT_HARDOP_SYNC_FAIL                       = 50002,
    ICRAFT_HARDOP_INVALID_COMPILE_TARGET          = 50003,
    ICRAFT_HARDOP_INVALID_INPUT_FTMPS             = 50004,
    ICRAFT_HARDOP_FORWARD_FAIL                    = 50005,
    ICRAFT_HARDOP_MEMCPY_FAIL                     = 50006,
    ICRAFT_HARDOP_INVALID_INPUT_MTYPE             = 50007,
    ICRAFT_HARDOP_GET_MMU_MODE_FAIL               = 50008,
    ICRAFT_HARDOP_INVALID_FTMP_DTYPE              = 50009,
    ICRAFT_HARDOP_SET_DTYPE_FAIL                  = 50010,
    ICRAFT_HARDOP_INVALID_OUTPUT_FTMPS            = 50011,
    ICRAFT_HARDOP_NULL_MMU_TABLE                  = 50012,
    ICRAFT_HARDOP_MMU_MODE_NOT_MATCH              = 50013,
    ICRAFT_HARDOP_FPGA_TIMEOUT                    = 50014,
    ICRAFT_HARDOP_DECONSTRUCT_FAIL                = 50015,
    ICRAFT_HARDOP_INVALID_VERSION                 = 50016,
    // input
    ICRAFT_INPUT_INVALID_COMPILE_TARGET           = 60001,
    ICRAFT_INPUT_INVALID_INPUT_FTMPS              = 60002,
    ICRAFT_INPUT_INVALID_OUTPUT_FTMPS             = 60003,
    ICRAFT_INPUT_DECONSTRUCT_FAIL                 = 60004,
    // output
    ICRAFT_OUTPUT_INVALID_COMPILE_TARGET          = 70001,
    ICRAFT_OUTPUT_INVALID_INPUT_FTMPS             = 70002,
    ICRAFT_OUTPUT_SYNC_FAIL                       = 70003,
    ICRAFT_OUTPUT_INVALID_OUTPUT_FTMPS            = 70004,
    ICRAFT_OUTPUT_DECONSTRUCT_FAIL                = 70005,
    // detpost
    ICRAFT_DETPOST_INVALID_COMPILE_TARGET         = 80001,
    ICRAFT_DETPOST_INVALID_INPUT_FTMPS            = 80002,
    ICRAFT_DETPOST_SYNC_FAIL                      = 80003,
    ICRAFT_DETPOST_INVALID_VERSION                = 80004,
    ICRAFT_DETPOST_START_FAIL                     = 80005,
    ICRAFT_DETPOST_INVALID_LAYER_EN               = 80006,
    ICRAFT_DETPOST_MALLOC_FAIL                    = 80007,
    ICRAFT_DETPOST_GET_IFM_FAIL                   = 80008,
    ICRAFT_DETPOST_INVALID_DTYPE                  = 80009,
    ICRAFT_DETPOST_TIME_OUT                       = 80010,
    ICRAFT_DETPOST_WRONG_DATA_SIZE                = 80011,
    ICRAFT_DETPOST_GET_VERSION_FAIL               = 80012,
    ICRAFT_DETPOST_INVALID_OUTPUT_FTMPS           = 80013,
    ICRAFT_DETPOST_DECONSTRUCT_FAIL               = 80014,
    // imagemake
    ICRAFT_IMAGEMAKE_INVALID_INPUT_FTMPS          = 90001,
    ICRAFT_IMAGEMAKE_INVALID_INPUT_PORT           = 90002,
    ICRAFT_IMAGEMAKE_INVALID_VERSION              = 90003,
    ICRAFT_IMAGEMAKE_MALLOC_FAIL                  = 90004,
    ICRAFT_IMAGEMAKE_INVALID_CHANNEL_TIMES        = 90005,
    ICRAFT_IMAGEMAKE_TIME_OUT                     = 90006,
    ICRAFT_IMAGEMAKE_INVALID_OUTPUT_FTMPS         = 90007,
    ICRAFT_IMAGEMAKE_DECONSTRUCT_FAIL             = 90008,
    //cast
    ICRAFT_CAST_INVALID_INPUT_FTMPS               = 100001,
    ICRAFT_CAST_INVALID_OUTPUT_FTMPS              = 100002,
    ICRAFT_CAST_DTC_WRONG_VERSION                 = 100003,
    ICRAFT_CAST_TIME_OUT                          = 100004,
    ICRAFT_CAST_SYNC_FAIL                         = 100005,
    ICRAFT_CAST_DECONSTRUCT_FAIL                  = 100006,
    ICRAFT_CAST_INVALID_VERSION                   = 100007,
    //hostop
    ICRAFT_HOSTOP_DECONSTRUCT_FAIL                = 110001,
    //warpaffine
    ICRAFT_WARPAFFINE_INVALID_DTYPE               = 120001,
    ICRAFT_WARPAFFINE_UPLOAD_GRID_DATA_FAIL       = 120002,
    ICRAFT_WARPAFFINE_INVALID_VERSION             = 120003,
    ICRAFT_WARPAFFINE_TIMEOUT                     = 120004,
    //segpost
    ICRAFT_SEGPOST_TIMEOUT         = 130001,
    ICRAFT_SEGPOST_INVALID_VERSION                = 130002,
    // list
    ICRAFT_LIST_NODE_MALLOC_ERROR                 = 200001,
    // queue
    ICRAFT_QUEUE_MALLOC_ERROR                     = 210001,
    ICRAFT_QUEUE_NULL                             = 210002,
    ICRAFT_QUEUE_NO_DATA_DEQUEUE                  = 210003,
    // hashtable
    ICRAFT_HASHTABLE_MALLOC_ERROR                 = 220001,
    ICRAFT_HASHTABLE_KEY_NOT_EXIST                = 220002,
    ICRAFT_HASHTABLE_DOUBLE_CREATE                = 220003,
    ICRAFT_HASHTABLE_NOT_CREATE                   = 220004,
    ICRAFT_HASHTABLE_INVALID_KEY                  = 220005,
    ICRAFT_HASHTABLE_INVALID_VALUE                = 220006,
    ICRAFT_HASHTABLE_HASH_FUNC_NULL               = 220007,
    // filesystem
    ICRAFT_FF_LOAD_FILE_FAIL                      = 230001,
    ICRAFT_FF_MALLOC_FAIL                         = 230002,
    ICRAFT_FF_CREATE_FILE_FAIL                    = 230003,
    ICRAFT_FF_WRITE_FILE_FAIL                     = 230004,
    ICRAFT_FF_CLOSE_FILE_FAIL                     = 230005,
    ICRAFT_FF_WRITE_FILE_CHECK_FAIL               = 230006,
    ICRAFT_FF_CREATE_DIR_FAIL                     = 230007,
    ICRAFT_FF_OPEN_DIR_FAIL                       = 230008,
    ICRAFT_FF_CLOSE_DIR_FAIL                      = 230009,    
    ICRAFT_FF_LOAD_FILE_BUFFER_NOT_NULL           = 230010,
    // gic
    ICRAFT_GIC_INIT_FAIL                          = 400001,
    ICRAFT_GIC_FORWARD_FAIL                       = 400002,
    ICRAFT_GIC_VERSION_WRONG                      = 400003,
    ICRAFT_CUSTOMOP_CHECK                         = 400004
}icraft_return;

#endif // ICRAFT_ERROR_H