/****************************************************************************/
/**
*
* @file ps_init.h
*
* This file is automatically generated
*
*****************************************************************************/
#ifndef _PS_INIT_H_
#define _PS_INIT_H_

#ifdef __cplusplus
extern "C" {
#endif

#define SLCR_REG_BASE      (0xE0026000)
#define SAC_REG_BASE       (0xE0040000)
#define DDR_UMC_REG_BASE   (0xE0029000)
#define DDR_PUB_REG_BASE   (0xE0027000)
#define DDR_ECC_REG_BASE   (0xE0026000)

#define OPCODE_EXIT       0U
#define OPCODE_CLEAR      1U
#define OPCODE_WRITE      2U
#define OPCODE_MASKWRITE  3U
#define OPCODE_MASKPOLL   4U
#define OPCODE_MASKDELAY  5U
#define NEW_PS_ERR_CODE   1
#define OPCODE_MASKCOPY   6U


#define PS_INIT_SUCCESS         (0)
#define PS_INIT_CORRUPT         (1)
#define PS_INIT_TIMEOUT         (2)
#define PS_POLL_FAILED_DDR_INIT (3)
#define PS_POLL_FAILED_DMA      (4)
#define PS_POLL_FAILED_PLL      (5)


#define APU_FREQ 999999990
#define AXI_FREQ 333333330
#define CSU_FREQ 99999999
#define AXI_DMA_FREQ 333333330
#define VPU_FREQ 499999995
#define GPU_FREQ 499999995
#define APU_GTC_FREQ 99999999
#define DDR_FREQ 374999996
#define FCLK0_FREQ 49999999
#define FCLK1_FREQ 100000000
#define FCLK2_FREQ 100000000
#define FCLK3_FREQ 100000000
#define DBG_FPD_FREQ 249999997
#define TPIU_FREQ 100000000
#define DBG_TSTMP_FREQ 249999997
#define USB0_FREQ 199999998
#define USB1_FREQ 100000000
#define ENET0_FREQ 124999998
#define ENET1_FREQ 100000000
#define SDIO_FREQ 99999999
#define SPI_FREQ 199999998
#define QSPI_FREQ 199999998
#define UART_FREQ 199999998
#define WDT_FREQ 83333332
#define GEM_TS_FREQ 83333332
#define TTC0_0_FREQ 83333332
#define TTC0_1_FREQ 83333332
#define TTC0_2_FREQ 83333332
#define TTC1_0_FREQ 83333332
#define TTC1_1_FREQ 83333332
#define TTC1_2_FREQ 83333332
#define PS_CLK_FREQ 33333333
#define CAN_FREQ 41666666
#define I2C_FREQ  83333332


/* Encode number of arguments in last nibble */
#define EMIT_EXIT()                   ( (OPCODE_EXIT      << 4 ) | 0 )
#define EMIT_CLEAR(addr)              ( (OPCODE_CLEAR     << 4 ) | 1 ) , addr
#define EMIT_WRITE(addr,val)          ( (OPCODE_WRITE     << 4 ) | 2 ) , addr, val
#define EMIT_MASKWRITE(addr,mask,val) ( (OPCODE_MASKWRITE << 4 ) | 3 ) , addr, mask, val
#define EMIT_MASKPOLL(addr,mask)      ( (OPCODE_MASKPOLL  << 4 ) | 2 ) , addr, mask
#define EMIT_MASKDELAY(addr,mask)     ( (OPCODE_MASKDELAY << 4 ) | 2 ) , addr, mask
#define EMIT_MASKCOPY(addrsrc,addrdst,masksrc,maskdst) \
                     ( (OPCODE_MASKCOPY << 4 ) | 4 ) , addrsrc, addrdst, masksrc, maskdst
int ps_config(unsigned long*);
int ps_init();
int ps_post_config();
int ps_debug();
char* getPSMessageInfo(unsigned key);

#ifdef __cplusplus
}
#endif

#endif /* protection macro */
